// Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
// All rights reserved.
// This file is a part of Klinok application

export type {
  AccountProfile,
  AppSnapshotDto,
  AuditRoleEntryDto,
  ControlSnapshot,
  DiagnosisCatalogGroup,
  DiagnosisCatalogOption,
  DiagnosisChoice,
  DiagnosisSectionValue,
  DiagnosisTaxonomyId,
  FreeTextSectionValue,
  GeneralDataSectionValue,
  InstrumentalFindingValue,
  InstrumentalStudyValue,
  InstrumentalTestsSectionValue,
  LaboratoryTestsSectionValue,
  MedicalEncounterInput,
  MedicalEncounterSection,
  MedicalEncounterSectionInputValue,
  MedicalEncounterSectionKind,
  MedicalRecordConfirmation,
  MedicalRecordDraft,
  MedicalSnapshot,
  OutcomeSectionValue,
  PetAccessGrant,
  PetAccessRequest,
  PetProfile,
  PetProfileInput,
  PetTransferRequest,
  TherapeuticAppointmentSectionValue,
  TherapeuticProblemValue,
  VaccinationSectionValue,
  WhatHappenedOption,
  WhatHappenedSectionValue,
} from "@klinok/contracts";
export {
  DIAGNOSIS_CATALOG,
  DIAGNOSIS_CATALOG_OPTIONS,
  DIAGNOSIS_TOP_LEVEL_OPTIONS,
  INSTRUMENTAL_STUDY_CATALOG,
  INSTRUMENTAL_STUDY_OPTIONS,
  availableInstrumentalFindingCatalog,
  canonicalizeInstrumentalFindingValues,
  MEDICAL_ENCOUNTER_SECTION_KINDS,
  isDiagnosisTaxonomyId,
  instrumentalFindingById,
  instrumentalStudyTypeById,
  LABORATORY_STUDY_CATALOG,
  LABORATORY_STUDY_OPTIONS,
  laboratoryIndicatorById,
  laboratoryStudyTypeById,
  normalizeLaboratoryTestsValue,
  normalizeInstrumentalTestsValue,
  WHAT_HAPPENED_LEAF_COUNT,
  WHAT_HAPPENED_TAXONOMY_IDS,
  WHAT_HAPPENED_TREE,
  canonicalWhatHappenedIds,
  isWhatHappenedTaxonomyId,
  whatHappenedLeafLabel,
  whatHappenedPath,
} from "@klinok/contracts";
