// Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
// All rights reserved.
// This file is a part of Klinok application

export type {
  AccountProfile,
  AppSnapshotDto,
  AuditRoleEntryDto,
  ControlSnapshot,
  DiagnosisCatalogGroup,
  DiagnosisCatalogOption,
  DiagnosisChoice,
  DiagnosisSectionValue,
  DiagnosisTaxonomyId,
  FreeTextSectionValue,
  GeneralDataSectionValue,
  LaboratoryTestsSectionValue,
  MedicalEncounterInput,
  MedicalEncounterSection,
  MedicalEncounterSectionInputValue,
  MedicalEncounterSectionKind,
  MedicalRecordConfirmation,
  MedicalRecordDraft,
  MedicalSnapshot,
  OutcomeSectionValue,
  PetAccessGrant,
  PetAccessRequest,
  PetProfile,
  PetProfileInput,
  TherapeuticAppointmentSectionValue,
  TherapeuticProblemValue,
  VaccinationSectionValue,
  WhatHappenedSectionValue,
} from "@klinok/contracts";
export {
  DIAGNOSIS_CATALOG,
  DIAGNOSIS_CATALOG_OPTIONS,
  MEDICAL_ENCOUNTER_SECTION_KINDS,
  isDiagnosisTaxonomyId,
  LABORATORY_STUDY_CATALOG,
  LABORATORY_STUDY_OPTIONS,
  laboratoryIndicatorById,
  laboratoryStudyTypeById,
  normalizeLaboratoryTestsValue,
} from "@klinok/contracts";
