#!/usr/bin/env bash
# Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of Klinok application

set -Eeuo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly PROJECT_DIR="$(cd -- "$SCRIPT_DIR" && pwd)"
readonly COMPOSE_FILE="${KLINOK_COMPOSE_FILE:-$PROJECT_DIR/docker-compose-ghrc.yml}"
readonly DOMAIN="${KLINOK_DOMAIN:-klinok.sw.consulting}"
readonly P2P_DOMAIN="${KLINOK_P2P_DOMAIN:-$DOMAIN}"
readonly REPLAY_QUARANTINE_EVENT_IDS="${KLINOK_REPLAY_QUARANTINE_EVENT_IDS:-}"
readonly DATA_ROOT="${KLINOK_DATA_ROOT:-/srv/klinok}"
readonly AUTH_DATA_DIR="${KLINOK_AUTH_HOST_DATA_DIR:-$DATA_ROOT/auth.v2/data}"
readonly P2P_DATA_DIR="${KLINOK_P2P_HOST_DATA_DIR:-$DATA_ROOT/p2p.v2/data}"
readonly CERTIFICATE_DIR="${KLINOK_CERTIFICATE_DIR:-$DATA_ROOT/certificate}"
readonly ENV_FILE="${KLINOK_ENV_FILE:-$PROJECT_DIR/klinok.env}"
readonly RECOVERY_BUNDLE="${KLINOK_RECOVERY_BUNDLE_PATH:-$PROJECT_DIR/bootstrap-recovery.bundle.json}"
readonly IMAGE_TAG="${KLINOK_IMAGE_TAG:-latest}"
readonly COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-klinok_cloud}"

KLINOK_SMTP_HOST="${KLINOK_SMTP_HOST:-mail.nic.ru}"
KLINOK_SMTP_PORT="${KLINOK_SMTP_PORT:-465}"
KLINOK_SMTP_SECURE="${KLINOK_SMTP_SECURE:-true}"
KLINOK_SMTP_USER="${KLINOK_SMTP_USER:-klinok@sw.consulting}"
KLINOK_SMTP_PASSWORD="${KLINOK_SMTP_PASSWORD:-Klinok\$123}"
KLINOK_SMTP_FROM="${KLINOK_SMTP_FROM:-Клинок <klinok@sw.consulting>}"

COMPOSE=(docker compose --project-name "$COMPOSE_PROJECT_NAME" --env-file "$ENV_FILE" -f "$COMPOSE_FILE")
TEMP_FILES=()

cleanup() {
  local path
  for path in "${TEMP_FILES[@]}"; do
    [[ ! -e "$path" ]] || rm -f -- "$path"
  done
}
trap cleanup EXIT

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

require_value() {
  local name="$1"
  [[ -n "${!name:-}" ]] || fail "$name must be set"
  [[ "${!name}" != *$'\n'* && "${!name}" != *$'\r'* ]] || fail "$name must not contain line breaks"
}

as_root() {
  if (( EUID == 0 )); then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo -- "$@"
  else
    fail "Root access is required to prepare $DATA_ROOT (install sudo or run this script as root)"
  fi
}

dotenv_quote() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$/\$\$}
  printf '"%s"' "$value"
}

write_environment() {
  local auth_key="$1"
  local bootstrap_key="$2"
  local env_dir env_tmp

  env_dir=$(dirname -- "$ENV_FILE")
  mkdir -p -- "$env_dir"
  env_tmp=$(mktemp "$env_dir/.klinok.env.XXXXXX")
  TEMP_FILES+=("$env_tmp")
  chmod 600 "$env_tmp"

  {
    printf '# Generated by scripts/bootstrap-cloud.sh; do not commit.\n'
    printf 'KLINOK_DOMAIN=%s\n' "$(dotenv_quote "$DOMAIN")"
    printf 'KLINOK_P2P_DOMAIN=%s\n' "$(dotenv_quote "$P2P_DOMAIN")"
    printf 'KLINOK_REPLAY_QUARANTINE_EVENT_IDS=%s\n' "$(dotenv_quote "$REPLAY_QUARANTINE_EVENT_IDS")"
    printf 'KLINOK_IMAGE_TAG=%s\n' "$(dotenv_quote "$IMAGE_TAG")"
    printf 'KLINOK_CERTIFICATE_DIR=%s\n' "$(dotenv_quote "$CERTIFICATE_DIR")"
    printf 'KLINOK_AUTH_HOST_DATA_DIR=%s\n' "$(dotenv_quote "$AUTH_DATA_DIR")"
    printf 'KLINOK_P2P_HOST_DATA_DIR=%s\n' "$(dotenv_quote "$P2P_DATA_DIR")"
    printf 'KLINOK_INTERNAL_EVENT_TOKEN=%s\n' "$(dotenv_quote "$KLINOK_INTERNAL_EVENT_TOKEN")"
    printf 'KLINOK_AUTH_ATTESTATION_PUBLIC_KEY=%s\n' "$(dotenv_quote "$auth_key")"
    printf 'KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY=%s\n' "$(dotenv_quote "$bootstrap_key")"
    printf 'KLINOK_SMTP_HOST=%s\n' "$(dotenv_quote "$KLINOK_SMTP_HOST")"
    printf 'KLINOK_SMTP_PORT=%s\n' "$(dotenv_quote "$KLINOK_SMTP_PORT")"
    printf 'KLINOK_SMTP_SECURE=%s\n' "$(dotenv_quote "$KLINOK_SMTP_SECURE")"
    printf 'KLINOK_SMTP_USER=%s\n' "$(dotenv_quote "${KLINOK_SMTP_USER:-}")"
    printf 'KLINOK_SMTP_PASSWORD=%s\n' "$(dotenv_quote "${KLINOK_SMTP_PASSWORD:-}")"
    printf 'KLINOK_SMTP_FROM=%s\n' "$(dotenv_quote "$KLINOK_SMTP_FROM")"
  } > "$env_tmp"

  mv -f -- "$env_tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

wait_for_health() {
  local service="$1"
  local attempts="${2:-60}"
  local container_id status

  for (( attempt = 1; attempt <= attempts; attempt += 1 )); do
    container_id=$("${COMPOSE[@]}" ps -q "$service")
    if [[ -n "$container_id" ]]; then
      status=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id")
      case "$status" in
        healthy|running) return 0 ;;
        unhealthy|exited|dead) fail "$service entered the $status state" ;;
      esac
    fi
    sleep 2
  done

  fail "Timed out waiting for $service to become healthy"
}

assert_container_json_key() {
  local service="$1"
  local variable_name="$2"
  local expected_json="$3"

  "${COMPOSE[@]}" exec -T "$service" node -e '
    const variableName = process.argv[1];
    const expected = JSON.parse(process.argv[2]);
    const actualText = process.env[variableName];
    if (!actualText) process.exit(2);
    const actual = JSON.parse(actualText);
    const canonical = (value) => JSON.stringify(value, Object.keys(value).sort());
    if (canonical(actual) !== canonical(expected)) process.exit(3);
  ' "$variable_name" "$expected_json" \
    || fail "$service does not use the persisted $variable_name trust key"
}

assert_runtime_trust_keys() {
  local runtime_config="$1"
  local auth_key="$2"
  local bootstrap_key="$3"

  printf '%s' "$runtime_config" | "${COMPOSE[@]}" exec -T auth-blue node -e '
    let input = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => { input += chunk; });
    process.stdin.on("end", () => {
      const runtime = JSON.parse(input);
      const expectedAuth = JSON.parse(process.argv[1]);
      const expectedBootstrap = JSON.parse(process.argv[2]);
      const canonical = (value) => JSON.stringify(value, Object.keys(value).sort());
      if (canonical(runtime.p2p?.authAttestationPublicKey) !== canonical(expectedAuth)) process.exit(2);
      if (canonical(runtime.p2p?.bootstrapSigningPublicKey) !== canonical(expectedBootstrap)) process.exit(3);
    });
  ' "$auth_key" "$bootstrap_key" \
    || fail "The public runtime configuration does not match the persisted trust keys"
}

diagnose() {
  local status=$?
  if (( status != 0 )) && [[ -f "$ENV_FILE" ]]; then
    printf '\nCloud bootstrap failed. Current service state:\n' >&2
    "${COMPOSE[@]}" ps --all >&2 || true
    printf '\nRecent service logs:\n' >&2
    "${COMPOSE[@]}" logs --no-color --tail=100 >&2 || true
  fi
  exit "$status"
}
trap diagnose ERR

for command in docker curl openssl; do
  require_command "$command"
done

[[ "$DOMAIN" == "klinok.sw.consulting" ]] || fail "The published UI image is configured for klinok.sw.consulting, not $DOMAIN"
[[ "$KLINOK_SMTP_PORT" =~ ^[0-9]+$ ]] || fail "KLINOK_SMTP_PORT must be numeric"
(( 10#$KLINOK_SMTP_PORT >= 1 && 10#$KLINOK_SMTP_PORT <= 65535 )) || fail "KLINOK_SMTP_PORT must be between 1 and 65535"
[[ "$KLINOK_SMTP_SECURE" == "true" || "$KLINOK_SMTP_SECURE" == "false" ]] || fail "KLINOK_SMTP_SECURE must be true or false"
for path in "$AUTH_DATA_DIR" "$P2P_DATA_DIR" "$CERTIFICATE_DIR" "$ENV_FILE" "$RECOVERY_BUNDLE"; do
  [[ "$path" == /* ]] || fail "Deployment paths must be absolute: $path"
done

for name in KLINOK_BOOTSTRAP_EMAIL KLINOK_BOOTSTRAP_PASSWORD KLINOK_RECOVERY_PASSPHRASE KLINOK_SMTP_HOST KLINOK_SMTP_FROM; do
  require_value "$name"
done
(( ${#KLINOK_BOOTSTRAP_PASSWORD} >= 6 && ${#KLINOK_BOOTSTRAP_PASSWORD} <= 128 )) || fail "KLINOK_BOOTSTRAP_PASSWORD must be 6-128 characters"
(( ${#KLINOK_RECOVERY_PASSPHRASE} >= 16 )) || fail "KLINOK_RECOVERY_PASSPHRASE must be at least 16 characters"
if [[ -n "${KLINOK_SMTP_USER:-}" || -n "${KLINOK_SMTP_PASSWORD:-}" ]]; then
  require_value KLINOK_SMTP_USER
  require_value KLINOK_SMTP_PASSWORD
fi

compose_version_output=""
if ! compose_version_output=$(docker compose version 2>&1); then
  fail "Docker Compose v2 could not start: $compose_version_output"
fi

readonly CERTIFICATE_PATH="$CERTIFICATE_DIR/s.crt"
readonly PRIVATE_KEY_PATH="$CERTIFICATE_DIR/s.key"
[[ -f "$CERTIFICATE_PATH" ]] || fail "TLS certificate not found: $CERTIFICATE_PATH"
[[ -f "$PRIVATE_KEY_PATH" ]] || fail "TLS private key not found: $PRIVATE_KEY_PATH"
openssl x509 -in "$CERTIFICATE_PATH" -noout -checkend 86400 >/dev/null || fail "TLS certificate is invalid or expires within 24 hours"
openssl x509 -in "$CERTIFICATE_PATH" -noout -checkhost "$DOMAIN" >/dev/null || fail "TLS certificate does not cover $DOMAIN"
openssl x509 -in "$CERTIFICATE_PATH" -noout -checkhost "$P2P_DOMAIN" >/dev/null || fail "TLS certificate does not cover $P2P_DOMAIN"
certificate_digest=$(openssl x509 -in "$CERTIFICATE_PATH" -pubkey -noout | openssl pkey -pubin -outform DER 2>/dev/null | openssl dgst -sha256)
private_key_digest=$(openssl pkey -in "$PRIVATE_KEY_PATH" -passin pass: -pubout -outform DER 2>/dev/null | openssl dgst -sha256)
[[ "$certificate_digest" == "$private_key_digest" ]] || fail "TLS certificate and private key do not match"

as_root install -d -m 0750 "$AUTH_DATA_DIR" "$P2P_DATA_DIR"
as_root chown 1000:1000 "$AUTH_DATA_DIR" "$P2P_DATA_DIR"
as_root chmod 0750 "$AUTH_DATA_DIR" "$P2P_DATA_DIR"
as_root chown root:1000 "$CERTIFICATE_DIR"
as_root chmod 0750 "$CERTIFICATE_DIR"
as_root chown root:1000 "$PRIVATE_KEY_PATH"
as_root chmod 0640 "$PRIVATE_KEY_PATH"
as_root chmod 0644 "$CERTIFICATE_PATH"

export KLINOK_DOMAIN="$DOMAIN"
export KLINOK_P2P_DOMAIN="$P2P_DOMAIN"
export KLINOK_REPLAY_QUARANTINE_EVENT_IDS="$REPLAY_QUARANTINE_EVENT_IDS"
export KLINOK_IMAGE_TAG="$IMAGE_TAG"
export KLINOK_CERTIFICATE_DIR="$CERTIFICATE_DIR"
export KLINOK_AUTH_HOST_DATA_DIR="$AUTH_DATA_DIR"
export KLINOK_P2P_HOST_DATA_DIR="$P2P_DATA_DIR"
export KLINOK_SMTP_PORT KLINOK_SMTP_SECURE
export KLINOK_INTERNAL_EVENT_TOKEN="${KLINOK_INTERNAL_EVENT_TOKEN:-$(openssl rand -hex 32)}"

write_environment "" ""
"${COMPOSE[@]}" config --quiet
"${COMPOSE[@]}" pull

# The auth service must release its LevelDB lock before the one-off provisioner runs.
"${COMPOSE[@]}" stop ui-blue auth-blue >/dev/null 2>&1 || true
"${COMPOSE[@]}" run --rm --no-deps -T \
  -e KLINOK_BOOTSTRAP_EMAIL \
  -e KLINOK_BOOTSTRAP_PASSWORD \
  -e KLINOK_RECOVERY_PASSPHRASE \
  auth-blue node auth-node/dist/provision.js

KLINOK_AUTH_ATTESTATION_PUBLIC_KEY=$("${COMPOSE[@]}" run --rm --no-deps -T auth-blue node -e \
  "const fs=require('fs');process.stdout.write(JSON.stringify(JSON.parse(fs.readFileSync('/data/provisioned/auth-attestation-public-key.json'))))")
KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY=$("${COMPOSE[@]}" run --rm --no-deps -T auth-blue node -e \
  "const fs=require('fs');process.stdout.write(JSON.stringify(JSON.parse(fs.readFileSync('/data/provisioned/bootstrap-public-anchor.json')).signingPublicKey))")
export KLINOK_AUTH_ATTESTATION_PUBLIC_KEY KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY
write_environment "$KLINOK_AUTH_ATTESTATION_PUBLIC_KEY" "$KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY"

recovery_dir=$(dirname -- "$RECOVERY_BUNDLE")
mkdir -p -- "$recovery_dir"
recovery_tmp=$(mktemp "$recovery_dir/.bootstrap-recovery.XXXXXX")
TEMP_FILES+=("$recovery_tmp")
chmod 600 "$recovery_tmp"
"${COMPOSE[@]}" run --rm --no-deps -T auth-blue node -e \
  "const fs=require('fs');process.stdout.write(fs.readFileSync('/data/provisioned/bootstrap-recovery.bundle.json','utf8'))" > "$recovery_tmp"
if [[ -e "$RECOVERY_BUNDLE" ]]; then
  cmp -s "$recovery_tmp" "$RECOVERY_BUNDLE" || fail "Refusing to overwrite a different recovery bundle at $RECOVERY_BUNDLE"
else
  mv -- "$recovery_tmp" "$RECOVERY_BUNDLE"
  chmod 600 "$RECOVERY_BUNDLE"
fi

"${COMPOSE[@]}" up -d --force-recreate p2p-blue
wait_for_health p2p-blue
"${COMPOSE[@]}" up -d --force-recreate auth-blue
wait_for_health auth-blue
"${COMPOSE[@]}" up -d --force-recreate ui-blue

for (( attempt = 1; attempt <= 60; attempt += 1 )); do
  if curl --fail --silent --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/api/auth/session" >/dev/null; then
    break
  fi
  sleep 2
done
curl --fail --silent --show-error --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/api/auth/session" >/dev/null \
  || fail "The HTTPS authentication endpoint did not become ready"
runtime_config=$(curl --fail --silent --show-error --resolve "$DOMAIN:443:127.0.0.1" "https://$DOMAIN/config.json") \
  || fail "The public runtime configuration could not be read"
assert_container_json_key auth-blue KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY "$KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY"
assert_container_json_key p2p-blue KLINOK_AUTH_ATTESTATION_PUBLIC_KEY "$KLINOK_AUTH_ATTESTATION_PUBLIC_KEY"
assert_container_json_key p2p-blue KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY "$KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY"
assert_runtime_trust_keys "$runtime_config" "$KLINOK_AUTH_ATTESTATION_PUBLIC_KEY" "$KLINOK_BOOTSTRAP_SIGNING_PUBLIC_KEY"

#unset KLINOK_BOOTSTRAP_EMAIL KLINOK_BOOTSTRAP_PASSWORD KLINOK_RECOVERY_PASSPHRASE
trap - ERR

printf '\nKlinok cloud deployment is ready.\n'
printf '  Application: https://%s\n' "$DOMAIN"
printf '  Compose environment: %s\n' "$ENV_FILE"
printf '  Recovery bundle: %s\n' "$RECOVERY_BUNDLE"
printf '\nMove the recovery bundle to encrypted offline storage and keep its passphrase separately.\n'
